# SPDX-FileCopyrightText: 2021 Belcan Advanced Solution
# SPDX-FileCopyrightText: 2021 Kaelan Thijs Fouwels <kaelan.thijs@fouwels.com>
#
# SPDX-License-Identifier: MIT

services:
  nginx:
    image: ghcr.io/fouwels/nginx:dev
    build:
      dockerfile: Dockerfile
      context: "./"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config_example/nginx:/config:ro
