# SPDX-FileCopyrightText: 2021 Belcan Advanced Solution
#
# SPDX-License-Identifier: MIT

services:
  nginx:
    image: registry2.lagoni.co.uk/lagoni-engineering/nginx:dev
    build:
      dockerfile: Dockerfile
      context: "./"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config_example/nginx:/config:ro
